version: 2

sources:
  - name: raw_data_circle
    description: Circle sportswear raw data lw
    tables: 
      - name: raw_cc_stock
        description: product stock data
      - name: raw_cc_sales
        description: sales of product
        tests:
          - unique:
              column_name: "(product_id || '-' || date_date)"

models:
  - name: stg_raw_data_circle__raw_cc_sales
    description: stage sales data
  - name: stg_raw_data_circle__raw_cc_stock
    description: stage stock data
    tests:
      - unique:
          column_name: product_id
  - name: int_stock__sales
    description: sales and stock combined